confluent/docker_utils/dub.py

File exists:
$ dub path-wait /etc/ssh/sshd_config 40
$ echo $?
0
File doesn't exist:
$ dub path-wait /etc/ssh/sshd_config2 40
/etc/ssh/sshd_config2 does not exist
Command [/usr/local/bin/dub path-wait /etc/ssh/sshd_config2 40] FAILED !
$ echo $?
1
File created while waiting:
$ dub path-wait /etc/ssh/sshd_config2 40 &
[1] 59660
$ sudo touch /etc/ssh/sshd_config2
$ fg
-bash: fg: job has terminated
[1]+  Done                    dub path-wait /etc/ssh/sshd_config2 40

Add dub path-wait command

---

confluent/docker_utils/cub.py

This adds ksql-server-ready and control-center-ready, modeled after https://github.com/confluentinc/confluent-docker-utils/pull/11

ST-1340: added ksql-server-ready and control-center-ready

---

confluent/docker_utils/dub.py
test/test_docker_utils.py

This change should solve cp-docker-image issue #488

Extend underscores for dub.env_to_props

---

requirements.txt

@confluentinc/tools what would be a good way to verify that this doesn't affect the rendered output? Any example usage of `dub.py template` that I can look at?

ST-3962: Update jinja2 version to latest

---

confluent/docker_utils/dub.py
test/test_docker_utils.py

`exit_if_all_absent` returns 'True' in all cases.

fix false positive bug in "dub ensure-atleast-one"

---

confluent/docker_utils/cub.py

**Context:**
Based off of #47 
In many CP images we already have a [log4j property ](https://github.com/confluentinc/kafka-images/blob/703e800d87acaf060b6eadd8c8bcf06470898579/zookeeper/Dockerfile.ubi8#L74)file at `/etc/$COMPONENT/log4j.properties`, which is configurable by customers and documented [here](https://docs.confluent.io/platform/current/installation/docker/operations/logging.html#log4j-log-levels). We want CP images to use said `log4j.properties` files.
**Changes**
Use component-specific log4j config files which are found at `/etc/$COMPONENT/log4j.properties`, or `/etc/cp-base-new-/log4j.properties` by default. `$COMPONENT` is an environment variable which is defined by individual CP repos, e.g. [kafka-mqtt here](https://github.com/confluentinc/kafka-mqtt-images/blob/master/kafk …

Use component-specific log4j config files

---

README.md

Fix the broken documentation link

---

requirements.txt

Updating cryptography package to address CVE-2023-23931

fix for CVE-2023-23931  (CVE-286)

---

.github/pull_request_template.md

This changes the pull_request_template.md to be much simpler than it is currently. The current template is overly complicated and many people do not fill it out before creating pull requests. The hope is that this new streamlined template will result in people filling in the PR description.
Copied the template contents into this PR description and used it for writing this description.

DP-11448: add/update pull_request_template.md

---

requirements.txt

Another update for cryptography package.

update cryptography package

---

requirements.txt

Update dependencies to address CVEs:
CVE-2023-49083  in cryptography
CVE-2023-48795  in paramiko

APPSEC-3502: update cryptography and paramiko packages

---

service.yml

Enable semaphore build to start work on migrating to semaphore.

minor: enable semaphore

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
requirements.txt

Migrate jenkins build logic to semaphore. 
Additional changes: 
- pin pyyaml as newer versions cannot be installed in py3 (similar issue: https://github.com/confluentinc/paas-utils/pull/134)
- add project.yaml from https://github.com/confluentinc/confluent-docker-utils/pull/69
Tests work per PR build. Release partially tested until publish in prev pr builds.

feat: semaphore migration

---

.semaphore/semaphore.yml

Install twine in release stage. 
Test install in previous build.

minor: install twine

---

Jenkinsfile

Sempahore build is running. We can deprecate jenkins builds.

minor: deprecate jenkinsfile

---

requirements.txt

Updated cryptography to address [CVE-2023-50782](https://nvd.nist.gov/vuln/detail/CVE-2023-50782)

APPSEC-xyz: update cryptography package

---

requirements.txt

Previous change includes 5.4.0. CVE requests 5.4.1+.

minor: ensure pyyaml version ~=5.4.1

---

requirements.txt

Resolve CVE: CVE-2024-26130
https://cryptography.io/en/latest/changelog/#v42-0-4
Existing tests

APPSEC-3786: Update cryptography version

---

requirements.txt

pin idna package to version 3.7

update idna to 3.7

---

service.yml

This changes the CI configuration to run on forked pull requests (in addition to the default values, which are now explicitly listed)
PR checks

run CI on forked pull requests

---

service.yml

Reverts confluentinc/confluent-docker-utils#86
This didn't work as expected. I was wrong.

Revert "run CI on forked pull requests"

---

setup.py

This manually increments the patch version by 1. The master build currently fails because of a mismatch between this version and the latest tag version.
PR checks

manually increment version

---

service.yml

enable automerge

---

.github/CODEOWNERS

Transfer ownership to CP build and release team
N/A

Transfer ownership to CP build and release team
