confluentinc/confluent-docker-utils

- confluent/docker_utils/cub.py
@confluentinc/caas 
This class path is not correct. Found this issue in healthcheck testing.
#jar -tf /usr/share/java/cc-base/utility-belt-4.0.0-20171127.075423-84.jar
.....
io/confluent/kafkaensure/cli/TopicEnsureCommand.class
.....
> fix the classpath.

- confluent/docker_utils/cub.py
Verified with
```bash
confluent-docker-utils/confluent/docker_utils $ python -c 'import cub; import sys; sys.argv = ["cub", "connect-ready", "localhost", "8083", "10"]; print cub.main()'
```
> ST-1531: add connect-ready to cub

- requirements.txt
https://jenkins.confluent.io/job/confluentinc/job/ksql-images/job/master/894/consoleFull reports that [INFO] _=/usr/bin/env
[INFO] ===> User
[INFO] uid=0(root) gid=0(root) groups=0(root)
[INFO] ===> Configuring ...
[INFO] Traceback (most recent call last):
[INFO]   File "/usr/local/bin/dub", line 6, in <module>
[INFO]     from pkg_resources import load_entry_point
[INFO]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
[INFO] 
[INFO]     @_call_aside
[INFO]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
[INFO] 
[INFO]     f(*args, **kwargs)
[INFO]   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
[INFO] 
[INFO]     working_set = …
> Add paramiko 2.4.2 to the list

- requirements.txt
The version of PyYAML used by the older version of docker-compose has a security vulnerability. This new version of docker compose uses the latest version of PyYAML.
> SEC-645: Upgrading version of docker-compose to use latest version of PyYAML

- requirements.txt
ksql images are current failing because 
```
ImportError: No module named six
```
which seems starts from yesterday. I have not yet root cause what cause the issue, but that change can fix the problem.
> Update module six

- requirements.txt
Confluent Docker Images are failing to build:
```
17:01:52  ==================================== ERRORS ====================================
17:01:52  ___________________ ERROR collecting test/test_base_image.py ___________________
17:01:52  /var/tmp/confluent/lib/python2.7/site-packages/_pytest/python.py:507: in _importtestmodule
17:01:52      mod = self.fspath.pyimport(ensuresyspath=importmode)
17:01:52  /var/tmp/confluent/lib/python2.7/site-packages/py/_path/local.py:704: in pyimport
17:01:52      __import__(modname)
17:01:52  /var/tmp/confluent/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
17:01:52      exec(co, mod.__dict__)
17:01:52  test/test_base_image.py:4: in <module>
17:01:52      import confluent.docker_utils as utils
17:01:52 …
```
> Pin pyrsistent bellow 0.17.0

- requirements.txt
* Specifically urllib3 & CVE-2020-26137
Removed the pyresilient pin, as that was done for python27 compatible packages (The Debian Docker Images), going forward, `master` will be for python3-compatible packages (CP 6.0 +). For CP < 5.5, I've made a branch from `v0.40.0` called `python27-compat` which is where we can maintain python27 dependencies.
Testing the change here: https://github.com/confluentinc/common-docker/pull/116 in 6.0.x, builds and it installs a newer version of urllib3:
```
15:43:25  [INFO] Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 attrs-20.3.0 bcrypt-3.2.0 boto3-1.9.128 botocore-1.12.253 cached-property-1.5.2 certifi-2020.12.5 cffi-1.14.4 chardet-3.0.4 confluent-docker-utils-0.0.41 cryptography-3.2.1 docker-3.7.2 docker-compose-1.25.2 …
```
> Bump requests version to pull in newer versions of python packages that address some CVEs

- requirements.txt
- setup.py
- tox.ini
- Loosening dependency requirements to stay on Major version to get
automatic patch updates (Looking for a Jinja-2.11.3 update)
- Also officially dropping py27 support with this update - enforced in setup.py, and removed in tox.ini.
Helper PR in docker-common shows the UBI image was installed with:
```
[2021-02-10T00:38:51.911Z] [INFO] Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 PyYAML-5.4.1 attrs-20.3.0 bcrypt-3.2.0 boto3-1.17.4 botocore-1.20.5 cached-property-1.5.2 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 confluent-docker-utils-0.0.42 cryptography-3.4.4 distro-1.5.0 docker-4.4.1 docker-compose-1.28.2 dockerpty-0.4.1 docopt-0.6.2 idna-2.10 importlib-metadata-3.4.0 jmespath-0.10.0 jsonschema-3.2.0 mock-4.0.3 paramiko-2.7.2 pycparser-2.20 pynacl-1.4.0 pyrsistent-0.17.3 …
```
> UPDATE: Loosen dependency requirements

- confluent/docker_utils/dub.py
If I understand this correctly, `CONTROL_CENTER_STREAMS_WITH___DASH` should result in `controlcenter.streams.with-dash`, not `controlcenter.streams.with_dash`.
> env_to_props: Fix example in docstring

- confluent/docker_utils/cub.py
Test against `cp-demo`:
```
./cub.py control-center-ready localhost 9022 5 --secure --ignore_cert && \
./cub.py kr-ready localhost 8086 5 --secure --ignore_cert --username superUser --password superUser && \
./cub.py sr-ready localhost 8085 5 --secure --ignore_cert --username superUser --password superUser && \
./cub.py connect-ready localhost 8083 5 --secure --ignore_cert --username superUser --password superUser && \
./cub.py ksql-server-ready localhost 8089 5 --secure --ignore_cert --username superUser --password superUser && \
echo "success"
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1006: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: …
```
> ST-6542: Add username/password options to cub *-ready scripts

- Jenkinsfile
- requirements.txt
- setup.py
Upgrade Python to 3.6.15 as requested in https://confluentinc.atlassian.net/browse/DP-7604 . Python 3.6.15 is [the latest for 3.6](https://www.python.org/downloads/release/python-3615/ ), addressing CVE https://nvd.nist.gov/vuln/detail/CVE-2021-3737. _This is a blocker for CFK patch releases tomorrow._
Fix the master branch which has been failing for a few months now. These changes include:
- Use `docker-debian-jdk8` nodelabel instead
- Pin markupsafe to 2.0.1 (as 2.1.0 [no longer includes soft_unicode](https://github.com/aws/aws-sam-cli/issues/3661))
**Follow-Up**
Once confluent-docker-utils has a new tag published, we will need to update common-docker in https://github.com/confluentinc/common-docker/commits/master/base/requirements.txt to have it used for our CFK and CP images
> Require python >=3.6.15 and fix failing master branch

- setup.py
Following exception request granted [here](https://confluentinc.atlassian.net/browse/DP-7604) , we do not need to upgrade Python to 3.6.15 at this time and will look into upgrading to 3.9 next quarter
> [minor] Relax Python requirement back to >=3.6

- confluent/docker_utils/cub.py
Address PR comments from #48 
- Fix typo in `ensure_topic()`
- Check for file existence for component-specific config, else default to cp-base-new's log4j.properties
After this is merged to master, I'll bump common-docker to point to the newly published version of `confluent-docker-utils` (similar to this [previous version bump](https://github.com/confluentinc/common-docker/pull/241)), including common-docker 5.4.x and 5.5.x which are currently pinned to older version for compatibility issues. Then will kick off some updated `cp-docker-images-overlay` builds.
> Fix typo and check file existence

- .github/CODEOWNERS
I am updating the reference to the "tools" team in the code owners file. Our new GitHub team name is "DevProd".
> DP-7231: Updating codeowners from tools to devprod team.

- tox.ini
`homedir` substitution is no longer supported for tox new version as well. refer to: https://tox.wiki/en/latest/config.html#environment-variable-substitutions
It's weird that the last PR build is successful despite it is still using `homedir`
update:  loos like the PR build didn't run the test.
> replace homedir

- .github/CODEOWNERS
The GitHub team `builds-automations-and-repositories` used to be named `DevProd`.
This PR updates the CODEOWNERS file to reflect the new team name.
> DP-7231: Rename DevProd to builds-automations-and-repositories in CODEOWNERS

- MANIFEST.in
Copy of https://github.com/confluentinc/confluent-docker-utils/pull/85
> This should allow sdists to install correctly.
>
> Fixes: Issue https://github.com/confluentinc/confluent-docker-utils/issues/84
PR checks
> fix: add `MANIFEST.in` file for packaging

- .semaphore/semaphore.yml
- requirements.txt
- test-requirements.txt
- tox.ini
This changes a few things related to dependency management:
1. Removes dev dependencies from `requirements.txt` and puts them in `test-requirements.txt` instead
2. Removes transitive dependencies from `requirements.txt` 
3. Pins dependency versions `requirements.txt` and `test-requirements.txt`
4. Moves dependencies from the Semaphore pipeline into `test-requirements.txt`
PR checks
> improve handling of dev dependencies

- .semaphore/semaphore.yml
This changes the release process so the branch with the incremented version is pushed before the git tag and CodeArtifact push. When the git tag and branch are pushed in the same command, one can succeed and one can fail. This typically happens when multiple PRs are merged at the same time. This causes a breakage because the branch is the source of truth for the version. If the git tag or the latest CodeArtifact version is ahead of the branch version, then the release process will attempt to overwrite a pre-existing tag or CodeArtifact version and it will fail. This gets it into a state where all subsequent releases fail.
N/A - can only be tested on master
> push branch before tag during release

- .semaphore/semaphore.yml
- test-requirements.txt
In https://github.com/confluentinc/confluent-docker-utils/pull/119, the version in `setup.py` was manually incremented to match CodeArtifact and the git tag. However, the master branch is now failing like https://semaphore.ci.confluent.io/jobs/5dfadf4d-5952-4095-811f-10bbeb814b94#L311. This is because `bumpversion` still sees the current version as n-1.  It's not clear to me why. This changes the logic to explicitly pass in the current version to `bumpversion`. The current version will come from `setup.py` as the definitive source of truth.
> determine the current version using setuptools

- test-requirements.txt
This removes the `Mako` and `MarkupSafe` test dependencies. These dependencies are unused.
PR checks
> remove mako and markupsafe dependencies

- tox.ini
This changes the pip installs to not run in quiet mode. There is currently a failure in the installs in the https://github.com/confluentinc/confluent-docker-utils/pull/140 CI job, but there isn't enough debugging information to determine why.
PR checks
> Change pip installs to not use -q

- .semaphore/semaphore.yml
This changes the Semaphore job to use Python 3.9. Python 3.8 is now EOL. Not bumping major version because there isn't a hard requirement on Python > 3.8 by any runtime dependency.
PR checks
> upgrade to python 3.9

- confluent/docker_utils/cub.py
- test/test_docker_utils.py
This PR adds support to use log4j2 configuration file when running cub commands. It will work along with log4j and log4j2 both to allow CP 7.x and CP 8.x compatibility. 
log4j2 configuration will be used if `USE_LOG4J_2` env variable is set else it will default to continue using log4j configuration.
Added basic unit tests for this change.
> CPBR-2474: add support for using log4j2 
